services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - vendor-data:/var/www/html/vendor
      - node-modules-data:/var/www/html/node_modules
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "8080:8000"
      - "5173:5173"
      - "5432:5432"
      - "6543:6543"
      - "6380:6379"

volumes:
  vendor-data:
  node-modules-data:
  postgres-data:
