services:
  web:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    depends_on:
      - app
    ports:
      - "8000:80"

  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    env_file:
      - .env
    environment:
      DOCKER_MODE: production
      CONTAINER_ROLE: app
    volumes:
      - ./:/var/www/html
      - storage-data:/var/www/html/storage
    depends_on:
      - db
      - redis

  queue:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    env_file:
      - .env.production
    environment:
      DOCKER_MODE: production
      CONTAINER_ROLE: queue
    volumes:
      - ./:/var/www/html
      - storage-data:/var/www/html/storage
    depends_on:
      - db
      - redis

  scheduler:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    env_file:
      - .env
    environment:
      DOCKER_MODE: production
      CONTAINER_ROLE: scheduler
    volumes:
      - ./:/var/www/html
      - storage-data:/var/www/html/storage
    depends_on:
      - db
      - redis

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: driverpay
      POSTGRES_USER: driverpay
      POSTGRES_PASSWORD: driverpay
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine

volumes:
  storage-data:
  postgres-data:
