services:
  web:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    depends_on:
      - app
    ports:
      - "8000:80"

  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    env_file:
      - .env.production
    environment:
      DOCKER_MODE: production
      CONTAINER_ROLE: app
    volumes:
      - ./:/var/www/html
      - storage-data:/var/www/html/storage

  queue:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    env_file:
      - .env.production
    environment:
      DOCKER_MODE: production
      CONTAINER_ROLE: queue
    volumes:
      - ./:/var/www/html
      - storage-data:/var/www/html/storage

  scheduler:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    env_file:
      - .env.production
    environment:
      DOCKER_MODE: production
      CONTAINER_ROLE: scheduler
    volumes:
      - ./:/var/www/html
      - storage-data:/var/www/html/storage

volumes:
  storage-data:
